### ISSUE TITLE
Error: Call to a member function getContext() on boolean

### ISSUE THREAD

**Issue by mgomez-dgt** [sonata-project/SonataClassificationBundle#180] opened 2016-04-07 16:51 UTC
Stack Trace
in vendor/sonata-project/classification-bundle/Controller/CategoryAdminController.php at line 79   -
        if (!$currentContext) {
            $mainCategory   = current($rootCategories);
            $currentContext = $mainCategory->getContext();
        } else {
            foreach ($rootCategories as $category) {
                if ($currentContext->getId() != $category->getContext()->getId()) {

**Comment by OskarStark** [comment] 2016-04-12 12:39
do you have at least one category?

**Comment by PBXg33k** [comment] 2016-04-17 10:34
I think the problem is that the template expects at least one category, but the user cannot add the first category by using the Admin interface.

I solved it on my setup by manually inserting a single 'context' and 'category' directly into the database.
Not the best solution, but it got me passed the error.

**Comment by jojonaloha** [comment] 2016-11-08 21:32
I'm having the same error. I've followed the installation instructions on https://sonata-project.org/bundles/classification/2-x/doc/reference/installation.html

I also ran `php app/console sonata:classification:fix-context` to see if that would resolve the issue, but I still get this error when I click on "Categories" from the Sonata Admin.

I think the code should at least check for this condition, even if it throws an Exception that gives a better explanation of what needs to be done.

**Comment by core23** [comment] 2016-11-09 15:28
Please use the new issue template @mgomez-dgt 

This would help a lot!

**Comment by gremo** [comment] 2016-11-23 13:06
This error is actually solved first running `php app/console sonata:classification:fix-context` **and then** browsing gallery and media listings (assuming you have SonataMediaBundle installed).

I agree it should be fixed ASAP.

**Comment by greg0ire** [comment] 2016-11-23 19:37
@gremo @jojonaloha if you want to help, do what OPs didn't do : 

- please post **links** to relevant pieces of code;
- please post a stack trace (what he posted is a code block, only one line of the stack).

**Closed** 2016-12-29 17:51 UTC
