### ISSUE TITLE
Error removing category Sonata Classification Bundle

### ISSUE THREAD

**Issue by pekindenis** [sonata-project/SonataClassificationBundle#28] opened 2014-03-24 09:15 UTC
Hello,

I have installed Classification bundle and also install its depends bundle, I have configured all steps from http://sonata-project.org/bundles/classification/master/doc/index.html

I created catalog:
-Root
--category1(parent root)
---category2(parent category1)
--category3(parent root)

If delete subcategory the entire directory will be removed.
how to fix it ?

**Comment by core23** [comment] 2016-08-27 12:43
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.

**Comment by jordisala1991** [comment] 2018-02-26 22:02
This issue was fixed long ago. Closing

**Closed by jordisala1991** 2018-02-26 22:02 UTC
Labels: pending author
