### ISSUE TITLE
"Position" field in CategoryAdmin only shows "0" all the time

### ISSUE THREAD

**Issue by blaues0cke** [sonata-project/SonataClassificationBundle#97] opened 2015-03-20 09:39 UTC
When I change the value of "position" its saved correctly in the database. But the field only shows "0". Bug or feature?

When I change line 103 in `CategoryAdmin.php` from:

```
->add('position', 'integer', array('required' => false, 'data' => 0))
```

to:

```
->add('position', 'integer', array('required' => false))
```

everything works fine.

![img_239_-_312x216 1](https://cloud.githubusercontent.com/assets/5159398/6749114/5460bcbe-ceed-11e4-8717-49a00ce9b49c.png)

**Comment by core23** [comment] 2016-08-27 15:59
Have you checked this against the latest stable / master version? @blaues0cke

**Comment by jordisala1991** [comment] 2018-04-01 17:18
No answer since 2016

Closing as unable to reproduce the issue.

**Closed by jordisala1991** 2018-04-01 17:18 UTC
Labels: pending author
