### ISSUE TITLE
How to use classificationBundle in my owner entity

### ISSUE THREAD

**Issue by meddridi** [sonata-project/SonataClassificationBundle#162] opened 2015-11-23 09:08 UTC
sorry, my question is how to use the bundle in my bundle for example i need to add category for an entity called course, how can i do that? i seen the doc and install it but i don't find how to add category in a specific entity

**Comment by core23** [comment] 2016-08-12 15:41
Duplicate of #170

**Closed by core23** 2016-08-12 15:41 UTC
